version: "3.3"
services: 
  talent_app:
    container_name: talent-service
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "7000:7000"
    network_mode: host
    restart: always